name: react test                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - master                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js 20          # Node.js 20 사용
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
      
      - name: Generate build          # React Build
        run: npm run build
        env:
          CI: ""
